name: Python Style Checker
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Choose the Python version you need for your project.
    
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
    
      - name: pycodestyle check
        uses: andymckay/pycodestyle-action@0.1.3
