name: Python Style Checker
on: [push]
jobs:
  checks-pep8-compliance:
    runs-on: ubuntu-latest
    steps:
        - uses: andymckay/pycodestyle-action@0.1.3
        - run: pycodestyle --first Day-57-Flask-Jinja-Templating/main.py
